name: AllocX CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-11 \
            g++-11 \
            cmake \
            python3-pip \
            clang-format

      - name: Configure and Build
        run: |
          cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run Tests
        run: |
          pytest tests --verbose
